2013-06-11 20:29:16
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 30, in run
  File "./sublimesvn/proc.py", line 71, in get_wc_root
  File "./sublimesvn/proc.py", line 113, in find_wc_root
KeyError: u'/Users/markdunphy/Sites/furthered/sdk'
2013-06-11 20:29:21
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 30, in run
  File "./sublimesvn/proc.py", line 71, in get_wc_root
  File "./sublimesvn/proc.py", line 113, in find_wc_root
KeyError: u'/Users/markdunphy/Sites/furthered/sdk'
2013-06-11 20:29:28
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 30, in run
  File "./sublimesvn/proc.py", line 71, in get_wc_root
  File "./sublimesvn/proc.py", line 113, in find_wc_root
KeyError: u'/Users/markdunphy/Sites/furthered/sdk'
2013-06-11 20:29:32
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 30, in run
  File "./sublimesvn/proc.py", line 71, in get_wc_root
  File "./sublimesvn/proc.py", line 113, in find_wc_root
KeyError: u'/Users/markdunphy/Sites/furthered/sdk'
2013-06-11 20:29:35
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 30, in run
  File "./sublimesvn/proc.py", line 71, in get_wc_root
  File "./sublimesvn/proc.py", line 113, in find_wc_root
KeyError: u'/Users/markdunphy/Sites/furthered/sdk'
2013-06-21 08:52:55
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 528, in run
  File "./sublimesvn/proc.py", line 897, in run
TypeError: coercing to Unicode: need string or buffer, NoneType found
2013-07-16 13:57:29
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 18, in run_with_except_hook
  File "./sublimesvn/status.py", line 528, in run
  File "./sublimesvn/proc.py", line 897, in run
TypeError: coercing to Unicode: need string or buffer, NoneType found
2013-09-30 15:47:35
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:47:39
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:47:41
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:47:41
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:47:43
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:53:29
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:53:30
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:53:30
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:53:31
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:53:36
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:53:40
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
2013-09-30 15:55:40
Traceback (most recent call last):
  File "./sublimesvn/threads.py", line 23, in run_with_except_hook
  File "./sublimesvn/listeners.py", line 31, in run
  File "./sublimesvn/proc.py", line 80, in get_wc_root
  File "./sublimesvn/proc.py", line 181, in find_wc_root
ProcessError: svn: The path '.' appears to be part of a Subversion 1.7 or greater
working copy.  Please upgrade your Subversion client to use this
working copy.
